spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      max-poll-records: 500
      properties:
        request.timeout.ms: 305000
        max.poll.interval.ms: 100000


application:
  kafka:
    topics:
      helloworld: helloworld.t
    group:
      helloworld: hello